workflows:
sample-workflow:
name: Codemagic Sample Workflow
max_build_duration: 120
instance_type: mac_mini_m1
environment:
vars:
BUNDLE_ID: "com.md.calenderapp"
name: Build ipa for distribution
script: | 
xcode-project build-ipa \
--project "Calendar.xcodeproj" \
--scheme "$XCODE_SCHEME"
artifacts:
  - build/ios/ipa/*.ipa
  - /tmp/xcodebuild_logs/*.log
  - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
  - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
